using NUnit.Framework;
using SennenRpg.Core.Data;

namespace SennenRpg.Tests;

[TestFixture]
public class TileMapDataParserTests
{
    // Exact base64 from DungeonFloor1.tscn Walls layer (40 tiles, all atlas 2,6)
    private const string Floor1WallsBase64 = "AAD+//7/AAACAAYAAAD///7/AAACAAYAAAAAAP7/AAACAAYAAAABAP7/AAACAAYAAAACAP7/AAACAAYAAAADAP7/AAACAAYAAAAEAP7/AAACAAYAAAAFAP7/AAACAAYAAAAGAP7/AAACAAYAAAAHAP7/AAACAAYAAAAIAP7/AAACAAYAAAAJAP7/AAACAAYAAAAKAP7/AAACAAYAAAAKAP//AAACAAYAAAAKAAAAAAACAAYAAAAKAAEAAAACAAYAAAAKAAIAAAACAAYAAAAKAAMAAAACAAYAAAAKAAQAAAACAAYAAAAKAAUAAAACAAYAAAAKAAYAAAACAAYAAAAJAAYAAAACAAYAAAAIAAYAAAACAAYAAAAHAAYAAAACAAYAAAAGAAYAAAACAAYAAAAFAAYAAAACAAYAAAAEAAYAAAACAAYAAAADAAYAAAACAAYAAAACAAYAAAACAAYAAAABAAYAAAACAAYAAAAAAAYAAAACAAYAAAD//wYAAAACAAYAAAD+/wYAAAACAAYAAAD+/wUAAAACAAYAAAD+/wQAAAACAAYAAAD+/wMAAAACAAYAAAD+/wIAAAACAAYAAAD+/wEAAAACAAYAAAD+/wAAAAACAAYAAAD+////AAACAAYAAAA=";

    // Exact base64 from DungeonFloor1.tscn Ground layer (77 tiles, no walls)
    private const string Floor1GroundBase64 = "AAAIAAQAAAABAAcAAAADAAQAAAAAAAcAAAAEAAQAAAAAAAYAAAAFAAQAAAABAAYAAAAGAAQAAAAAAAYAAAAHAAQAAAAAAAYAAAADAAMAAAAAAAYAAAAEAAMAAAAAAAYAAAAFAAMAAAAAAAYAAAAGAAMAAAAAAAYAAAAHAAMAAAAAAAYAAAAIAAMAAAAAAAYAAAAJAAMAAAAAAAYAAAAJAAQAAAAAAAYAAAAJAAUAAAAAAAYAAAAIAAUAAAAAAAYAAAAHAAUAAAAAAAYAAAAGAAUAAAAAAAYAAAAFAAUAAAAAAAYAAAAEAAUAAAAAAAYAAAADAAUAAAAAAAYAAAACAAUAAAAAAAYAAAACAAQAAAAAAAYAAAACAAMAAAAAAAYAAAD/////AAAAAAYAAAAAAP//AAAAAAYAAAABAP//AAAAAAYAAAACAP//AAAAAAYAAAADAP//AAAAAAYAAAAEAP//AAAAAAYAAAAFAP//AAAAAAYAAAAGAP//AAAAAAYAAAAHAP//AAAAAAYAAAAIAP//AAAAAAYAAAAJAP//AAAAAAYAAAAJAAAAAAAAAAYAAAAJAAEAAAAAAAYAAAAJAAIAAAAAAAYAAAAIAAIAAAAAAAYAAAAIAAEAAAAAAAYAAAAIAAAAAAABAAYAAAAHAAAAAAAAAAYAAAAHAAEAAAAAAAYAAAAHAAIAAAAAAAYAAAAGAAEAAAAAAAYAAAAFAAIAAAAAAAYAAAAFAAEAAAAAAAYAAAAFAAAAAAABAAYAAAAGAAAAAAAAAAYAAAAGAAIAAAABAAYAAAAEAAEAAAAAAAYAAAAEAAAAAAAAAAYAAAAEAAIAAAAAAAYAAAADAAIAAAAAAAYAAAADAAEAAAAAAAYAAAADAAAAAAABAAYAAAACAAAAAAAAAAYAAAACAAEAAAAAAAYAAAACAAIAAAAAAAYAAAABAAAAAAAAAAYAAAAAAAAAAAABAAYAAAAAAAEAAAAAAAYAAAAAAAIAAAAAAAYAAAABAAIAAAAAAAYAAAABAAMAAAAAAAYAAAABAAQAAAAAAAYAAAABAAUAAAAAAAYAAAAAAAUAAAAAAAYAAAD//wUAAAAAAAYAAAD//wQAAAAAAAYAAAD//wMAAAAAAAYAAAD//wIAAAAAAAYAAAD//wEAAAAAAAYAAAD//wAAAAAAAAYAAAABAAEAAAAAAAYAAAAAAAMAAAAAAAYAAAAAAAQAAAABAAYAAAA=";

    // Exact base64 from DungeonFloor2.tscn Ground layer BEFORE fix (119 tiles: 77 ground + 42 walls mixed)
    private const string Floor2MixedBase64 = "AAADAAQAAAAAAAcAAAAIAAQAAAABAAcAAAAJAP//AAABAAYAAAAIAP//AAAAAAYAAAAHAP//AAAAAAYAAAAGAP//AAAAAAYAAAAFAP//AAAAAAYAAAAEAP//AAAAAAYAAAADAP//AAAAAAYAAAACAP//AAAAAAYAAAABAP//AAAAAAYAAAAAAP//AAABAAYAAAD/////AAAAAAYAAAD//wAAAAAAAAYAAAD//wEAAAAAAAYAAAD//wIAAAAAAAYAAAD//wMAAAAAAAYAAAD//wQAAAAAAAYAAAAAAAQAAAABAAYAAAABAAQAAAAAAAYAAAAAAAMAAAAAAAYAAAABAAMAAAAAAAYAAAACAAMAAAAAAAYAAAADAAMAAAAAAAYAAAAEAAMAAAAAAAYAAAAFAAMAAAAAAAYAAAAGAAMAAAAAAAYAAAAHAAMAAAAAAAYAAAAIAAMAAAAAAAYAAAAJAAMAAAAAAAYAAAAJAAQAAAAAAAYAAAAHAAQAAAAAAAYAAAAGAAQAAAAAAAYAAAAFAAQAAAAAAAYAAAAEAAQAAAAAAAYAAAACAAQAAAAAAAYAAAD//wUAAAABAAYAAAAAAAUAAAAAAAYAAAABAAUAAAAAAAYAAAACAAUAAAAAAAYAAAADAAUAAAAAAAYAAAAEAAUAAAAAAAYAAAAFAAUAAAAAAAYAAAAGAAUAAAAAAAYAAAAHAAUAAAAAAAYAAAAIAAUAAAAAAAYAAAAJAAUAAAAAAAYAAAAJAAEAAAAAAAYAAAAJAAIAAAAAAAYAAAAIAAIAAAAAAAYAAAAHAAIAAAAAAAYAAAAGAAIAAAABAAYAAAAFAAIAAAAAAAYAAAAEAAIAAAAAAAYAAAADAAIAAAAAAAYAAAACAAIAAAAAAAYAAAABAAIAAAAAAAYAAAAAAAIAAAAAAAYAAAAAAAEAAAAAAAYAAAABAAEAAAABAAYAAAACAAEAAAAAAAYAAAADAAEAAAAAAAYAAAAEAAEAAAAAAAYAAAAFAAEAAAAAAAYAAAAGAAEAAAAAAAYAAAAHAAEAAAAAAAYAAAAIAAEAAAAAAAYAAAAIAAAAAAAAAAYAAAAJAAAAAAAAAAYAAAAHAAAAAAAAAAYAAAAGAAAAAAAAAAYAAAAFAAAAAAAAAAYAAAAEAAAAAAAAAAYAAAADAAAAAAABAAYAAAACAAAAAAAAAAYAAAABAAAAAAAAAAYAAAAAAAAAAAAAAAYAAAAKAAYAAAACAAYAAAAJAAYAAAACAAYAAAAIAAYAAAACAAYAAAAHAAYAAAACAAYAAAAGAAYAAAACAAYAAAAFAAYAAAACAAYAAAAEAAYAAAACAAYAAAADAAYAAAACAAYAAAACAAYAAAACAAYAAAABAAYAAAACAAYAAAAAAAYAAAACAAYAAAD//wYAAAACAAYAAAD+/wYAAAACAAYAAAD+/wUAAAACAAYAAAD+/wQAAAACAAYAAAD+/wMAAAACAAYAAAD+/wIAAAACAAYAAAD+/wEAAAACAAYAAAD+/wAAAAACAAYAAAD+////AAACAAYAAAD+//7/AAACAAYAAAD///7/AAACAAYAAAAAAP7/AAACAAYAAAABAP7/AAACAAYAAAACAP7/AAACAAYAAAADAP7/AAACAAYAAAAEAP7/AAACAAYAAAAFAP7/AAACAAYAAAAGAP7/AAACAAYAAAAHAP7/AAACAAYAAAAHAP3/AAACAAYAAAAIAP3/AAACAAYAAAAIAP7/AAACAAYAAAAJAP7/AAACAAYAAAAKAP7/AAACAAYAAAAKAP//AAACAAYAAAAKAAAAAAACAAYAAAAKAAEAAAACAAYAAAAKAAIAAAACAAYAAAAKAAMAAAACAAYAAAAKAAQAAAACAAYAAAAKAAUAAAACAAYAAAA=";

    [Test]
    public void Decode_Floor1Walls_Returns40TilesAllAtlas2_6()
    {
        var tiles = TileMapDataParser.Decode(Floor1WallsBase64);

        Assert.That(tiles, Has.Count.EqualTo(40));
        Assert.That(tiles, Has.All.Matches<TileEntry>(t => t.AtlasX == 2 && t.AtlasY == 6));
        Assert.That(tiles, Has.All.Matches<TileEntry>(t => t.SourceId == 0));
    }

    [Test]
    public void Decode_Floor1Ground_Returns77TilesNoWalls()
    {
        var tiles = TileMapDataParser.Decode(Floor1GroundBase64);

        Assert.That(tiles, Has.Count.EqualTo(77));
        Assert.That(tiles, Has.None.Matches<TileEntry>(t => t.AtlasX == 2 && t.AtlasY == 6));
    }

    [Test]
    public void Encode_Roundtrip_Floor1Walls()
    {
        var tiles = TileMapDataParser.Decode(Floor1WallsBase64);
        string reencoded = TileMapDataParser.Encode(tiles);

        Assert.That(reencoded, Is.EqualTo(Floor1WallsBase64));
    }

    [Test]
    public void Encode_Roundtrip_Floor1Ground()
    {
        var tiles = TileMapDataParser.Decode(Floor1GroundBase64);
        string reencoded = TileMapDataParser.Encode(tiles);

        Assert.That(reencoded, Is.EqualTo(Floor1GroundBase64));
    }

    [Test]
    public void SplitByClassification_Floor2_SeparatesWallsFromGround()
    {
        var allTiles = TileMapDataParser.Decode(Floor2MixedBase64);
        var wallCoords = new HashSet<(short, short)> { (2, 6) };

        var (ground, walls) = TileMapDataParser.SplitByClassification(allTiles, wallCoords);

        Assert.That(walls, Has.Count.EqualTo(42));
        Assert.That(ground, Has.Count.EqualTo(77));
        Assert.That(ground.Count + walls.Count, Is.EqualTo(allTiles.Count));
        Assert.That(walls, Has.All.Matches<TileEntry>(t => t.AtlasX == 2 && t.AtlasY == 6));
        Assert.That(ground, Has.None.Matches<TileEntry>(t => t.AtlasX == 2 && t.AtlasY == 6));
    }

    [Test]
    public void GetUniqueAtlasCoords_Floor1Ground_ReturnsExpected()
    {
        var tiles = TileMapDataParser.Decode(Floor1GroundBase64);
        var coords = TileMapDataParser.GetUniqueAtlasCoords(tiles);

        Assert.That(coords, Is.EquivalentTo(new HashSet<(short, short)>
        {
            (0, 6), (0, 7), (1, 6), (1, 7)
        }));
    }

    [Test]
    public void Encode_EmptyList_ReturnsHeaderOnly()
    {
        string result = TileMapDataParser.Encode(new List<TileEntry>());
        byte[] data = Convert.FromBase64String(result);

        Assert.That(data, Has.Length.EqualTo(2));
        Assert.That(data[0], Is.EqualTo(0));
        Assert.That(data[1], Is.EqualTo(0));
    }
}
